#: schema https://github.com/cloudflare/workers-sdk/files/12887590/wrangler.schema.json
name = "classroom-remix"

main = "./server.ts"
workers_dev = true
account_id = "1f507c7933d231cc8051d23050bda6ab"
compatibility_date = "2024-05-12"

services = [
  { binding = "AUTH", service = "classroom-service-auth" }
]

kv_namespaces = [
  { binding = "CACHE", id = "f47062b8b39c4c289d354d8d839d7c51" }
]

[placement]
mode = "smart"

[site]
bucket = "./build/client"

[build]
command = "pnpm run build"

[vars]
ROOMS_COUNTER_SINGLETON_ID = "rooms-counter"

[[d1_databases]]
binding = "DB"
database_name = "classroom-prod"
database_id = "1c112361-3257-4c41-ad7d-58d766bdb20f"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "classroom-preview"
database_id = "2545125e-68fa-4dba-9b48-bc3f56c8fc26"
